### ISSUE TITLE
Advice on MIDI parsing

### ISSUE THREAD

**Issue by dreamwieber** [andres-fr/iamusica_demo#2]
Hi, 

I've been trying to piece together a little standalone script to go from wav->midi – mostly to better understand what each of these modules is doing.

Wanted to see if there's any advice on exporting the data frame values to midi? I have it kinda/sorta working but it's not quite right. I'm using some hacks to properly offset the notes given the NUM_KEYS, and the timing seems off. Also, can't really get overlapping notes chords figured out.

Anyway, would love if you could point me in the right direction – I've looked pretty deeply through the demo code, but it's a big application so I might be missing where the magic happens. Or perhaps there's a simple df->MIDI explanation somewhere.

Thanks for your time, and very interesting project!

**Comment by andres-fr** [comment]
Hi @dreamwieber thanks for your interest!

Unfortunately, the functionality to export dataframes into midi is not supported in this demo, and probably this is out of scope anyways. One major reason is that the model only detects the onsets, and the offsets are also needed for midi. This was basically an exploratory research project of limited scope.

Now, lets say you want to implement it anyway, assigning some note duration for the offsets. The functionality to convert from midi into Python internals is in this companion repository: https://github.com/andres-fr/iamusica_training/tree/master/ov_piano/data

Which uses the `mido` library. I'm almost positive that you can use that library to convert said internals into a midi object that you can then export to filesystem.

I hope this helps! I'm going to close the issue but feel free to reopen if you have any follow up questions.

Cheers!  
Andres

**Comment by dreamwieber** [comment]
Ah, thanks for the lead! 

For what I'm toying around with, the lack of note-off detection is fine. I'll check this out, thanks again :)

**Comment by dreamwieber** [comment]
And just so I'm not chasing ghosts, the code in both repos is meant to detect overlapping notes (chords) and not just single sequential notes, correct? 

The companion was helpful – I was already using Mido, but there were some hop size / sample rate and num_notes conversions that I was missing. So, I'm able to extract MIDI of something like a simple C major scale, and some more complex pieces. The timing is a little better. But when I try a simple chord test, I'm getting bizarre results.

No pressure to respond – I get this repo is a companion to the paper, but figured I'd ask just in case. Either way, cool stuff!

**Comment by dreamwieber** [comment]
Ok, actually – don't waste your time. I'm doing a simple chord test and from my debug output the individual notes are definitely in the data frame at the correct timing. Issue must lay with how I'm converting timing information to MIDI. So, please don't worry about responding and sorry for the spam!

**Comment by andres-fr** [comment]
Glad it works on your end! Let me know if you want to do a PR for the midi export, or if anything else comes up
